### ISSUE TITLE
Input type="hidden" ?

### ISSUE THREAD

**Issue by tommymb** [tommymb/registration-form#1]
@muxlowc

Trying to finish this assignment from a few weeks ago, all my screenshots match and the markbot expectations are all met except for one saying it's expecting to see an input type="hidden". 

I'm not sure where I would put a hidden input or why I'd need to since nothing in the screenshots shows any of the inputs as hidden.

![Screen Shot 2020-04-14 at 6 47 21 PM](https://user-images.githubusercontent.com/43139261/79281661-3dbe8b00-7e81-11ea-8f57-47ecbf3527a6.png)
![Screen Shot 2020-04-14 at 6 53 04 PM](https://user-images.githubusercontent.com/43139261/79281665-3f884e80-7e81-11ea-9df7-5b4d47364c33.png)
![Screen Shot 2020-04-14 at 6 52 08 PM](https://user-images.githubusercontent.com/43139261/79281671-41eaa880-7e81-11ea-943f-4905f60d1784.png)
![Screen Shot 2020-04-14 at 6 52 43 PM](https://user-images.githubusercontent.com/43139261/79281676-431bd580-7e81-11ea-904e-e30563529c73.png)

.

**Comment by muxlowc** [comment]
@tommymb ah yah, this is a weird one ( i think it was leftover from Thomas' old classes)
Just add this code right below your button div, but before you close your form:

```
    <input type="hidden" name="_subject" value="Request to join the mission">
  </form>
```
